---
abstract: 'Slide Shows in Vim'
author:
  - 'Ingy döt Net <ingy@ingy.net>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Vroom
name: Vroom
no_index:
  directory:
    - inc
    - t
requires:
  File::HomeDir: 0.99
  IO::All: 0.44
  Template::Toolkit::Simple: 0.16
  Term::Size: 0.207
  YAML::XS: 0.38
  perl: 5.6.1
resources:
  homepage: https://github.com/drbean/vroom-pm/tree
  license: http://dev.perl.org/licenses/
  repository: https://github.com/drbean/vroom-pm.git
version: 0.29
