#!/usr/bin/bash

HOME='/home/drbean'
echo "Who am I? I am '$(whoami)' at '$HOME'" 1>&2

git config user.name 'Dr Bean'
git config user.email 'drbean@freeshell.org'
# git config credential.helper "cache --timeout 3600  \
# 	--socket $HOME/.config/git/credential/socket"
git config core.askPass '/home/drbean/gh'

for c in global local ; do
	echo -e "\\n$c helper: "
	git config --$c --get credential.helper
	for u in name email ; do
		echo -e "\n$c $u: " ;
		git config --$c --get user.$u
	done
done 1>&2

repo=$1
rev=$2
info=$(svnlook info $repo -r $rev)
mess=$(sed -n -e '4p' <<<$info )

look_changed=$(svnlook changed $repo -r $rev)
while read p ; do
	repo_path=${p##* }
	if [[ $repo_path == *edit/branch/* ]] ; then
		prof_wc_file_path=${repo_path#edit/branch/}
		file_path=${prof_wc_file_path#*/}
		file=${prof_wc_file_path##*/}
		prof_wc=${prof_wc_file_path%/$file_path}
		prof=${prof_wc_file_path%%/*}
		if [[ $prof == *chinte* ]] ; then
			file_path=${file_path#*/}
			if [[ $file == issues.md ]] ; then
				continue
			fi
		fi
		profedit_dir=$HOME/profedit
		dev_dir=$profedit_dir/$prof
		target=$dev_dir/$file_path
	elif [[ $repo_path == *perlbrew* ]] ; then
		change=${repo_path#*perlbrew/}
		dev_dir=$HOME/dot/cygwin/perlbrew
		target=$dev_dir/$change
	else
		dev_dir=$HOME/${repo_path%/trunk*}
		target=$dev_dir/${look_changed##*trunk/}
	fi
	cd $dev_dir
	git add $target 1>&2
done <<<$(svnlook changed $repo -r $rev)

echo "repo_path=$repo_path,
prof_wc_file_path=$prof_wc_file_path,
file_path=$file_path,
file=$file,
prof_wc=$prof_wc,
prof=$prof,
dev_dir=$dev_dir,
target=$target" 1>&2

whoami 1>&2
echo -e "\ngit status\n" 1>&2
git status 1>&2
echo -e "\ngit diff\n" 1>&2
git diff --cached 1>&2
# /usr/bin/git add $target 2>&1
echo -e "\ngit commit\n" 1>&2
git commit -m "$mess" 1<&2
# git push -u origin csyu
echo -e "\ngit push\n" 1>&2
git push 1>&2
/usr/bin/echo "commit target: $target message: '$mess' pwd: $(pwd)" 2>&1

# "$mess" happened?
# $target is?
# $(pwd)

# exit 2
exit 0
