#!/usr/bin/bash

HOME='/home/drbean'
echo "Who am I? I am '$(whoami)' at '$HOME'" 1>&2

git config user.name 'Dr Bean'
git config user.email 'drbean@freeshell.org'
# git config credential.helper "cache --timeout 3600  \
# 	--socket $HOME/.config/git/credential/socket"
git config core.askPass '/home/drbean/gh'

for c in global local ; do
	echo -e "\\n$c helper: "
	git config --$c --get credential.helper
	for u in name email ; do
		echo -e "\n$c $u: " ;
		git config --$c --get user.$u
	done
done 1>&2

repo=$1
rev=$2
info=$(svnlook info $repo -r $rev)
mess=$(sed -n -e '4p' <<<$info )

look_changed=$(svnlook changed $repo -r $rev)
while read p ; do
	path=${p##* }
	if [[ $path == *edit/branch/* ]] ; then
		prof_repo_file=${path#edit/branch/}
		file=${prof_repo_file##*/}
		prof_repo=${prof_repo_file%/$file}
		prof=${prof_repo_file%%/*}
		dev_dir=$HOME/profedit/$prof
		target=$dev_dir/$file
	else
		dev_dir=$HOME/${path%/trunk*}
		target=$dev_dir/${look_changed##*trunk/}
	fi
	cd $dev_dir
	git add $target 1>&2
done <<<$(svnlook changed $repo -r $rev)

echo "path=$path,
dev_dir=$dev_dir,
target=$target" 1>&2

whoami 1>&2
git status 1>&2
git diff 1>&2
# /usr/bin/git add $target 2>&1
git commit -m "$mess"
# git push -u origin csyu
git push
/usr/bin/echo "commit target: $target message: '$mess' pwd: $(pwd)" 2>&1

# "$mess" happened?
# $target is?
# $(pwd)

# exit 2
exit 0
