#!/usr/bin/bash

HOME='/home/drbean'
echo "Who am I? I am '$(whoami)' at '$HOME'" 1>&2

git config user.name 'Dr Bean'
git config user.email 'drbean@freeshell.org'
git config user.password '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'
git config credential.helper 'cache --timeout 3600
'
for c in global local ; do
	echo -e "\\n$c helper: "
	git config --$c --get credential.helper
	for u in name password email ; do
		echo -e "\n$c $u: " ;
		git config --$c --get user.$u
	done
done 1>&2

repo=$1
rev=$2
info=$(/usr/bin/svnlook info $repo -r $rev)
mess=$(sed -n -e '4p' <<<$info )

changes=$(/usr/bin/svnlook changed $repo -r $rev)
path=$(sed -n -e 's/^.*trunk\/\(.*\)$/\1/p' <<<$changes )
dev_dir=$(sed -n -E 's/^.*\s([[:alnum:]]*)\/.*$/\1/p' <<<$changes)

/usr/bin/cd /home/drbean/$dev_dir
/usr/bin/whoami 1>&2
/usr/bin/git status 1>&2
/usr/bin/git diff 1>&2
# /usr/bin/git add $path 2>&1
/usr/bin/git commit $path -m "$mess"
/usr/bin/git push
# /usr/bin/echo "commit path: $path message: '$mess' pwd: $(pwd)" 2>&1

# "$mess" happened?
# $path is?
# $(pwd)

exit 2
