#!env bash

instance=(mastodon.sdf.org none mastodon-japan.net duk.space g0v.social)
for n in 0 2 3 4 ; do
    screen -X -p $n stuff "toot --as drbean@${instance[$n]} tui -m cygstart^M"
    echo "In window $n, toot --as drbean@${instance[$n]} tui"
done
