# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# fedora22 ~/.bashrc

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
# User specific environment and startup programs

# https://cygwin.com/pipermail/cygwin/2023-February/253054.html
# eg, man -H ls
case $(uname) in
(CYGWIN_NT-*) export BROWSER=cygstart
esac

# LANG=ja_JP.UTF-8@cjkwide
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_COLLATE=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_NUMERIC=en_US.UTF-8
LC_MONETARY=en_US.UTF-8
LC_MESSAGES=en_US.UTF-8
LC_ALL=en_US.UTF-8
export LANG LC LC_CTYPE LC_COLLATE LC_TIME \
LC_NUMERIC LC_MONETARY LC_MESSAGES LC_ALL

# export TERM=screen

MANPATH=$HOME/edit/trunk/email/trurl/man:${MANPATH-}

export PATH=$PATH:"/cygdrive/c/Program Files/qutebrowser"
PATH=$PATH:$HOME/.local/bin:$HOME/bin
PATH=$PATH:$(cygpath $APPDATA/local/bin)

export PATH=/cygdrive/c/Program\ Files\ \(x86\)/Vim/vim90/:$PATH

PATH=$PATH:"/cygdrive/c/Program Files/nodejs/"
export PATH=$PATH:"/cygdrive/c/Program Files/nodejs/node_modules/yarn/bin"
# export PATH=$PATH:"/cygdrive/c/Users/$USER/node_modules/yarn/bin"
# export PATH=$PATH:"/home/$USER/node_modules/yarn/bin"

#greg
# export PATH=$HOME/.cabal/bin:$PATH
# /etc/profile.d/cabalinstall.sh does it for me
export HISTSIZE=50000

export EDITOR=v
# export EDITOR="/usr/pkg/bin/vim"

# ibus
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus

declare -a THEME=("AnnArbor" "Antibes" "Bergen" "Berkeley" "Berlin" "Boadilla" "boxes" "CambridgeUS" "Copenhagen" "Darmstadt" "default" "Dresden" "Frankfurt" "Goettingen" "Hannover" "Ilmenau" "JuanLesPins" "Luebeck" "Madrid" "Malmoe" "Marburg" "Montpellier" "PaloAlto" "Pittsburgh" "Rochester" "Singapore" "Szeged" "Warsaw")
declare -a COLOR=("albatross" "beaver" "beetle" "crane" "default" "dolphin" "dove" "fly" "lily" "orchid" "rose" "seagull" "seahorse" "sidebartab" "structure" "whale" "wolverine")
export THEME COLORTHEME

#greg
# screen needs 700 on socketdir?
if [ "$(uname)" == "CYGWIN_NT-6.1" ]; then
	export SCREENDIR=/cygdrive/c/tmp
	if [ ! -d $SCREENDIR ]; then
		mkdir $SCREENDIR
	fi
	chmod 700 $SCREENDIR
	export PATH=$PATH:/cygdrive/c/Users/$USER/Documents/gf-3.8/bin
	export GF_LIB_PATH=/cygdrive/c/$USER/Documents/gf-3.8/gf-3.8/lib/present
fi


export DESKTOP_SESSION=xmonad-mate
# .bashrc
