# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# fedora22 ~/.bashrc

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
# User specific environment and startup programs

export LANG=en_US.UTF8

PATH=$PATH:$HOME/.local/bin:$HOME/bin

#greg
# export PATH=$HOME/.cabal/bin:$PATH
# /etc/profile.d/cabalinstall.sh does it for me
export HISTSIZE=50000

export EDITOR=v

# ibus
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus

declare -a THEME=("AnnArbor" "Antibes" "Bergen" "Berkeley" "Berlin" "Boadilla" "boxes" "CambridgeUS" "Copenhagen" "Darmstadt" "default" "Dresden" "Frankfurt" "Goettingen" "Hannover" "Ilmenau" "JuanLesPins" "Luebeck" "Madrid" "Malmoe" "Marburg" "Montpellier" "PaloAlto" "Pittsburgh" "Rochester" "Singapore" "Szeged" "Warsaw")
declare -a COLOR=("albatross" "beaver" "beetle" "crane" "default" "dolphin" "dove" "fly" "lily" "orchid" "rose" "seagull" "seahorse" "sidebartab" "structure" "whale" "wolverine")
export THEME COLORTHEME

#greg
# screen needs 700 on socketdir?
if [ "$(uname)" == "CYGWIN_NT-10.1" ]; then
	export SCREENDIR=/cygdrive/c/tmp
	if [ ! -d $SCREENDIR ]; then
		mkdir $SCREENDIR
	fi
	chmod 700 $SCREENDIR
	export PATH=$PATH:/cygdrive/c/Users/owuser/Documents/gf-3.8/bin
	export GF_LIB_PATH=/cygdrive/c/owuser/Documents/gf-3.8/gf-3.8/lib/present
fi


export DESKTOP_SESSION=xmonad-mate
# .bashrc
